name:                qrandom
version:             0.1.0.0
github:              "jac3km4/qrandom"
license:             BSD3
author:              "jac3km4"
maintainer:          "jac3km4@gmail.com"
copyright:           "2019 jac3km4"

ghc-options: -Wall

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jac3km4/qrandom#readme>

dependencies:
- base >= 4.7 && < 5
- req
- free
- aeson
- text

library:
  source-dirs: src

tests:
  qrandom-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qrandom
    - data-default-class
